### ISSUE TITLE
Jobs with errors causes worker to unsubscribe from all queues

### ISSUE THREAD

**Issue by colman-hartinger** [akira/exq#478]
Exq config:
```
  start_on_application: false,
  scheduler_enable: true,
  mode: :default
 
 ###############################
 application.ex
 ###############################
 children = [
   Exq
 ]
```

Description:
A job with a failure that kills the worker process causes the worker node to unsubscribe all the queues indefinitely.

**Comment by ananthakumaran** [comment]
Could you share the error logs or a minimal example that reproduces the problem? I tried with the above config, but couldn't reproduce the problem.

**Comment by colman-hartinger** [comment]
Hmm I think it could possibly be an issue with exq_ui actually since when using that it's sending  a TSTP unsubscribe signal to the node for no reason

**Comment by ananthakumaran** [comment]
Could you upgrade exq_ui to the latest version. There was a bug which would
lead to the issue you mentioned. If you had the busy tab open and if you
restart exq_ui, it will end up treating the csrf token request as
unsubscribe request. This has been fixed in the latest release

**Comment by colman-hartinger** [comment]
I upgraded to exq_ui version 0.12.3 but the same thing is still happening. Heres an error log I have

```
warning: <%= live_component Component %> is deprecated, please use <.live_component module={Component} id="hello"/> inside HEEx templates instead

(phoenix_live_view 0.17.11) lib/phoenix_live_view/helpers.ex:497: Phoenix.LiveView.Helpers.live_component/1

(exq_ui 0.12.3) lib/exq_ui_web/templates/layout/live.html.heex:1: anonymous fn/2 in ExqUIWeb.LayoutView."live.html"/1

Received TSTP, unsubscribing from all queues module=Exq.Node.Server pid=<0.2943.0>
```

I can close this issue and reopen it in the exq_ui repo since this doesn't seem to be a bug with exq

**Comment by ananthakumaran** [comment]
Can you point to the master branch of exq_ui. I assumed it was released,
but it is still not released.
